### ISSUE TITLE
add_recipe to random forest workflow

### ISSUE THREAD

**Issue by drkamarul** [StatsGary/NHSRComm_TidyModels_Recipes#1]
Excellent tutorial https://github.com/StatsGary/NHSRComm_TidyModels_Recipes/blob/main/Building_a_TidyModel_for_classification_from_scratch_full_tutorial.Rmd

For codes between lines 422-425 (random forest), do you have any particular reason for not adding `add_recipe()`

**Comment by StatsGary** [comment]
Great point. I wanted the random forest model to work with the original training data without a recipe, but you could easily just add the same recipe as we have had throughout all the rest of the tutorials.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Kamarul ***@***.***>
Sent: Sunday, December 19, 2021 2:39:24 AM
To: StatsGary/NHSRComm_TidyModels_Recipes ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [StatsGary/NHSRComm_TidyModels_Recipes] add_recipe to random forest workflow (Issue #1)


Excellent tutorial https://github.com/StatsGary/NHSRComm_TidyModels_Recipes/blob/main/Building_a_TidyModel_for_classification_from_scratch_full_tutorial.Rmd

For codes between lines 422-425 (random forest), do you have any particular reason for not adding add_recipe()

**Comment by drkamarul** [comment]
Thanks for the answer!
